/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_sitechcrash_SitechCrash */

#ifndef _Included_com_example_sitechcrash_SitechCrash
#define _Included_com_example_sitechcrash_SitechCrash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_sitechcrash_SitechCrash
 * Method:    install
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_sitechcrash_SitechCrash_install
  (JNIEnv *, jclass);

/*
 * Class:     com_example_sitechcrash_SitechCrash
 * Method:    testcarsh
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_sitechcrash_SitechCrash_testcarsh
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
